[keyboard]
bindings = [
  { key = "C", mods = "Command", chars = "\u0003" },
  { key = "Back", mods = "Control", chars = "\u0017" },
  { key =  "Tab", mods = "Control", action = "SelectNextTab" },
  { key =  "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },
]

[font]
  size = 18.0

