#!/usr/bin/env bash
# Regenerate alacritty/colors.toml from colors/palette.sh.
# Run after editing palette.sh.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=palette.sh
source "$DIR/palette.sh"

cat > "$DIR/../alacritty/colors.toml" <<EOF
# Generated by colors/generate-alacritty-colors.sh. Do not edit by hand.
[colors.primary]
background = "$COLOR_BG"
foreground = "$COLOR_WHITE"

[colors.normal]
black   = "$COLOR_BLACK"
red     = "$COLOR_RED"
green   = "$COLOR_GREEN"
yellow  = "$COLOR_YELLOW"
blue    = "$COLOR_BLUE"
magenta = "$COLOR_MAGENTA"
cyan    = "$COLOR_CYAN"
white   = "$COLOR_WHITE"
EOF
touch "$DIR/../alacritty/alacritty.toml"

echo "Alacritty colors generated successfully at $DIR/../alacritty/colors.toml"
